-- MySQL Script generated by MySQL Workbench
-- Sun Jun 30 13:27:22 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Request for change of specialization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Request for change of specialization` (
  `idRequest for change of specialization` INT NOT NULL,
  `Justification of demand` VARCHAR(45) NOT NULL,
  `Previous Specialization` VARCHAR(45) NOT NULL,
  `Specialization to be transferred` VARCHAR(45) NOT NULL,
  `GPA` VARCHAR(45) NULL,
  `number of decision` INT NOT NULL,
  `Date of starting decision` VARCHAR(45) NOT NULL,
  `scientific level` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRequest for change of specialization`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Request for extension of scholarship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Request for extension of scholarship` (
  `idRequest for extension of scholarship` INT NOT NULL,
  `Degree if the extension is of a higher level` VARCHAR(45) NOT NULL,
  `Duration of study in the classroom` VARCHAR(45) NOT NULL,
  `GPA` VARCHAR(45) NOT NULL,
  `Duration of extension of scholarship` VARCHAR(45) NOT NULL,
  `Duration of the extension of the language stage` VARCHAR(45) NOT NULL,
  `Achieved by the scholarship during the academic period` VARCHAR(45) NOT NULL,
  `number of decision` INT NOT NULL,
  `Date of starting decision` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRequest for extension of scholarship`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`scientific journey`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`scientific journey` (
  `idscientific journey` INT NOT NULL,
  `Country` VARCHAR(45) NOT NULL,
  `Duration of the scientific trip` VARCHAR(45) NOT NULL,
  `the University` VARCHAR(45) NOT NULL,
  `Specialization` VARCHAR(45) NOT NULL,
  `Educational level` VARCHAR(45) NOT NULL,
  `number of decision` VARCHAR(45) NOT NULL,
  `Date of starting decision` INT NOT NULL,
  `scientific level` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idscientific journey`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Termination of scholarship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Termination of scholarship` (
  `idTermination of scholarship` INT NOT NULL,
  `Justification of demand` VARCHAR(45) NOT NULL,
  `The student's scholarship during the last study period` VARCHAR(45) NOT NULL,
  `The date required for it mission` VARCHAR(45) NOT NULL,
  `Duration of study in the classroom` VARCHAR(45) NOT NULL,
  `GPA` VARCHAR(45) NOT NULL,
  `number decision` INT NOT NULL,
  `Date of starting decision` VARCHAR(45) NOT NULL,
  `scientific level` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTermination of scholarship`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`University change request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`University change request` (
  `idUniversity change request` INT NOT NULL,
  `Justification of demand` VARCHAR(45) NOT NULL,
  `Previous University` VARCHAR(45) NOT NULL,
  `The university to be transferred to` VARCHAR(45) NOT NULL,
  `GPA` VARCHAR(45) NOT NULL,
  `number of  decision` INT NOT NULL,
  `Date of starting decision` VARCHAR(45) NOT NULL,
  `scientific level` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUniversity change request`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NewScholarship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NewScholarship` (
  `idNewScholarship` INT NOT NULL,
  `Specialization required` VARCHAR(45) NOT NULL,
  `Certified copy of the last scientific qualification` VARCHAR(45) NOT NULL,
  `Copy of passport` VARCHAR(45) NOT NULL,
  `Country of Scholarship` VARCHAR(45) NOT NULL,
  `Quality of acceptance` VARCHAR(45) NOT NULL,
  `beginning of the study` VARCHAR(45) NOT NULL,
  `Language of study` VARCHAR(45) NOT NULL,
  `The degree of scholarship required` VARCHAR(45) NOT NULL,
  `University` VARCHAR(45) NOT NULL,
  `University Admission Facility` VARCHAR(45) NOT NULL,
  `Parental confirmation` VARCHAR(45) NOT NULL,
  `Duration of study according to admission` VARCHAR(45) NOT NULL,
  `Attach the dispensing model` VARCHAR(45) NOT NULL,
  `CV` VARCHAR(45) NOT NULL,
  `Teachers' degree of measurement` VARCHAR(45) NOT NULL,
  `Attach the IELTS score` VARCHAR(45) NOT NULL,
  `number of  decision` INT NOT NULL,
  `Date of starting decision` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idNewScholarship`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.` postponement of scholarship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.` postponement of scholarship` (
  `id postponement of scholarship` INT NOT NULL,
  `Educational level` VARCHAR(45) NOT NULL,
  `Duration required to complete the scholarship` VARCHAR(45) NOT NULL,
  `Date required to continue the scholarship` VARCHAR(45) NOT NULL,
  `Date required for delayed scholarship` VARCHAR(45) NOT NULL,
  `GPA` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id postponement of scholarship`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Teacher` (
  `id` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `UserName` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `PhoneNumber` INT NOT NULL,
  `Gender` VARCHAR(45) NOT NULL,
  `Birth Date` VARCHAR(45) NOT NULL,
  `Job Number` INT NOT NULL,
  `Start of service` VARCHAR(45) NOT NULL,
  `Two-year evaluation` VARCHAR(45) NOT NULL,
  `Career_rank` VARCHAR(45) NOT NULL,
  `job_title` VARCHAR(45) NOT NULL,
  `University_of_Graduation` VARCHAR(45) NOT NULL,
  `Graduation Date` VARCHAR(45) NOT NULL,
  `Specialization` VARCHAR(45) NOT NULL,
  `Administration` VARCHAR(45) NOT NULL,
  `Degree` VARCHAR(45) NOT NULL,
  `Level of language` VARCHAR(45) NOT NULL,
  `Request for change of specialization_idRequest for change of specialization` INT NOT NULL,
  `Request for extension of scholarship_idRequest for extension of scholarship` INT NOT NULL,
  `scientific journey_idscientific journey` INT NOT NULL,
  `Termination of scholarship_idTermination of scholarship` INT NOT NULL,
  `University change request_idUniversity change request` INT NOT NULL,
  `NewScholarship_idNewScholarship` INT NOT NULL,
  ` postponement of scholarship_id postponement of scholarship` INT NOT NULL,
  PRIMARY KEY (`id`, `Request for change of specialization_idRequest for change of specialization`, `Request for extension of scholarship_idRequest for extension of scholarship`, `scientific journey_idscientific journey`, `Termination of scholarship_idTermination of scholarship`, `University change request_idUniversity change request`, `NewScholarship_idNewScholarship`, ` postponement of scholarship_id postponement of scholarship`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `userName_UNIQUE` (`UserName` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`Email` ASC) VISIBLE,
  UNIQUE INDEX `phoneNumber_UNIQUE` (`PhoneNumber` ASC) VISIBLE,
  INDEX `fk_Teacher_Request for change of specialization1_idx` (`Request for change of specialization_idRequest for change of specialization` ASC) VISIBLE,
  INDEX `fk_Teacher_Request for extension of scholarship1_idx` (`Request for extension of scholarship_idRequest for extension of scholarship` ASC) VISIBLE,
  INDEX `fk_Teacher_scientific journey1_idx` (`scientific journey_idscientific journey` ASC) VISIBLE,
  INDEX `fk_Teacher_Termination of scholarship1_idx` (`Termination of scholarship_idTermination of scholarship` ASC) VISIBLE,
  INDEX `fk_Teacher_University change request1_idx` (`University change request_idUniversity change request` ASC) VISIBLE,
  INDEX `fk_Teacher_NewScholarship1_idx` (`NewScholarship_idNewScholarship` ASC) VISIBLE,
  INDEX `fk_Teacher_ postponement of scholarship1_idx` (` postponement of scholarship_id postponement of scholarship` ASC) VISIBLE,
  CONSTRAINT `fk_Teacher_Request for change of specialization1`
    FOREIGN KEY (`Request for change of specialization_idRequest for change of specialization`)
    REFERENCES `mydb`.`Request for change of specialization` (`idRequest for change of specialization`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Teacher_Request for extension of scholarship1`
    FOREIGN KEY (`Request for extension of scholarship_idRequest for extension of scholarship`)
    REFERENCES `mydb`.`Request for extension of scholarship` (`idRequest for extension of scholarship`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Teacher_scientific journey1`
    FOREIGN KEY (`scientific journey_idscientific journey`)
    REFERENCES `mydb`.`scientific journey` (`idscientific journey`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Teacher_Termination of scholarship1`
    FOREIGN KEY (`Termination of scholarship_idTermination of scholarship`)
    REFERENCES `mydb`.`Termination of scholarship` (`idTermination of scholarship`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Teacher_University change request1`
    FOREIGN KEY (`University change request_idUniversity change request`)
    REFERENCES `mydb`.`University change request` (`idUniversity change request`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Teacher_NewScholarship1`
    FOREIGN KEY (`NewScholarship_idNewScholarship`)
    REFERENCES `mydb`.`NewScholarship` (`idNewScholarship`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Teacher_ postponement of scholarship1`
    FOREIGN KEY (` postponement of scholarship_id postponement of scholarship`)
    REFERENCES `mydb`.` postponement of scholarship` (`id postponement of scholarship`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Education Administration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Education Administration` (
  `idEducation Administration` INT NOT NULL,
  `phone` INT NOT NULL,
  `user name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `Date of Birth` VARCHAR(45) NOT NULL,
  `Job number` VARCHAR(45) NOT NULL,
  `Gender` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEducation Administration`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee of the Ministry of Education`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee of the Ministry of Education` (
  `idEmployee of the Ministry of Education` INT NOT NULL,
  `phone` INT NOT NULL,
  `user name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `Date of Birth` VARCHAR(45) NOT NULL,
  `Job number` VARCHAR(45) NOT NULL,
  `Gender` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEmployee of the Ministry of Education`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Education Administration_has_NewScholarship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Education Administration_has_NewScholarship` (
  `Education Administration_idEducation Administration` INT NOT NULL,
  `NewScholarship_idNewScholarship` INT NOT NULL,
  PRIMARY KEY (`Education Administration_idEducation Administration`, `NewScholarship_idNewScholarship`),
  INDEX `fk_Education Administration_has_NewScholarship_NewScholarsh_idx` (`NewScholarship_idNewScholarship` ASC) VISIBLE,
  INDEX `fk_Education Administration_has_NewScholarship_Education Ad_idx` (`Education Administration_idEducation Administration` ASC) VISIBLE,
  CONSTRAINT `fk_Education Administration_has_NewScholarship_Education Admi1`
    FOREIGN KEY (`Education Administration_idEducation Administration`)
    REFERENCES `mydb`.`Education Administration` (`idEducation Administration`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Education Administration_has_NewScholarship_NewScholarship1`
    FOREIGN KEY (`NewScholarship_idNewScholarship`)
    REFERENCES `mydb`.`NewScholarship` (`idNewScholarship`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee of the Ministry of Education_has_NewScholarship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee of the Ministry of Education_has_NewScholarship` (
  `Employee of the Ministry of Education_idEmployee of the Ministry of Education` INT NOT NULL,
  `NewScholarship_idNewScholarship` INT NOT NULL,
  PRIMARY KEY (`Employee of the Ministry of Education_idEmployee of the Ministry of Education`, `NewScholarship_idNewScholarship`),
  INDEX `fk_Employee of the Ministry of Education_has_NewScholarship_idx` (`NewScholarship_idNewScholarship` ASC) VISIBLE,
  INDEX `fk_Employee of the Ministry of Education_has_NewScholarship_idx1` (`Employee of the Ministry of Education_idEmployee of the Ministry of Education` ASC) VISIBLE,
  CONSTRAINT `fk_Employee of the Ministry of Education_has_NewScholarship_E1`
    FOREIGN KEY (`Employee of the Ministry of Education_idEmployee of the Ministry of Education`)
    REFERENCES `mydb`.`Employee of the Ministry of Education` (`idEmployee of the Ministry of Education`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employee of the Ministry of Education_has_NewScholarship_N1`
    FOREIGN KEY (`NewScholarship_idNewScholarship`)
    REFERENCES `mydb`.`NewScholarship` (`idNewScholarship`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee of the Ministry of Education_has_Request for extension of scholarship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee of the Ministry of Education_has_Request for extension of scholarship` (
  `Employee of the Ministry of Education_idEmployee of the Ministry of Education` INT NOT NULL,
  `Request for extension of scholarship_idRequest for extension of scholarship` INT NOT NULL,
  PRIMARY KEY (`Employee of the Ministry of Education_idEmployee of the Ministry of Education`, `Request for extension of scholarship_idRequest for extension of scholarship`),
  INDEX `fk_Employee of the Ministry of Education_has_Request for ex_idx` (`Request for extension of scholarship_idRequest for extension of scholarship` ASC) VISIBLE,
  INDEX `fk_Employee of the Ministry of Education_has_Request for ex_idx1` (`Employee of the Ministry of Education_idEmployee of the Ministry of Education` ASC) VISIBLE,
  CONSTRAINT `fk_Employee of the Ministry of Education_has_Request for exte1`
    FOREIGN KEY (`Employee of the Ministry of Education_idEmployee of the Ministry of Education`)
    REFERENCES `mydb`.`Employee of the Ministry of Education` (`idEmployee of the Ministry of Education`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employee of the Ministry of Education_has_Request for exte2`
    FOREIGN KEY (`Request for extension of scholarship_idRequest for extension of scholarship`)
    REFERENCES `mydb`.`Request for extension of scholarship` (`idRequest for extension of scholarship`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee of the Ministry of Education_has_Request for change of specialization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee of the Ministry of Education_has_Request for change of specialization` (
  `Employee of the Ministry of Education_idEmployee of the Ministry of Education` INT NOT NULL,
  `Request for change of specialization_idRequest for change of specialization` INT NOT NULL,
  PRIMARY KEY (`Employee of the Ministry of Education_idEmployee of the Ministry of Education`, `Request for change of specialization_idRequest for change of specialization`),
  INDEX `fk_Employee of the Ministry of Education_has_Request for ch_idx` (`Request for change of specialization_idRequest for change of specialization` ASC) VISIBLE,
  INDEX `fk_Employee of the Ministry of Education_has_Request for ch_idx1` (`Employee of the Ministry of Education_idEmployee of the Ministry of Education` ASC) VISIBLE,
  CONSTRAINT `fk_Employee of the Ministry of Education_has_Request for chan1`
    FOREIGN KEY (`Employee of the Ministry of Education_idEmployee of the Ministry of Education`)
    REFERENCES `mydb`.`Employee of the Ministry of Education` (`idEmployee of the Ministry of Education`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employee of the Ministry of Education_has_Request for chan2`
    FOREIGN KEY (`Request for change of specialization_idRequest for change of specialization`)
    REFERENCES `mydb`.`Request for change of specialization` (`idRequest for change of specialization`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee of the Ministry of Education_has_Termination of scholarship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee of the Ministry of Education_has_Termination of scholarship` (
  `Employee of the Ministry of Education_idEmployee of the Ministry of Education` INT NOT NULL,
  `Termination of scholarship_idTermination of scholarship` INT NOT NULL,
  PRIMARY KEY (`Employee of the Ministry of Education_idEmployee of the Ministry of Education`, `Termination of scholarship_idTermination of scholarship`),
  INDEX `fk_Employee of the Ministry of Education_has_Termination of_idx` (`Termination of scholarship_idTermination of scholarship` ASC) VISIBLE,
  INDEX `fk_Employee of the Ministry of Education_has_Termination of_idx1` (`Employee of the Ministry of Education_idEmployee of the Ministry of Education` ASC) VISIBLE,
  CONSTRAINT `fk_Employee of the Ministry of Education_has_Termination of s1`
    FOREIGN KEY (`Employee of the Ministry of Education_idEmployee of the Ministry of Education`)
    REFERENCES `mydb`.`Employee of the Ministry of Education` (`idEmployee of the Ministry of Education`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employee of the Ministry of Education_has_Termination of s2`
    FOREIGN KEY (`Termination of scholarship_idTermination of scholarship`)
    REFERENCES `mydb`.`Termination of scholarship` (`idTermination of scholarship`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee of the Ministry of Education_has_University change request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee of the Ministry of Education_has_University change request` (
  `Employee of the Ministry of Education_idEmployee of the Ministry of Education` INT NOT NULL,
  `University change request_idUniversity change request` INT NOT NULL,
  PRIMARY KEY (`Employee of the Ministry of Education_idEmployee of the Ministry of Education`, `University change request_idUniversity change request`),
  INDEX `fk_Employee of the Ministry of Education_has_University cha_idx` (`University change request_idUniversity change request` ASC) VISIBLE,
  INDEX `fk_Employee of the Ministry of Education_has_University cha_idx1` (`Employee of the Ministry of Education_idEmployee of the Ministry of Education` ASC) VISIBLE,
  CONSTRAINT `fk_Employee of the Ministry of Education_has_University chang1`
    FOREIGN KEY (`Employee of the Ministry of Education_idEmployee of the Ministry of Education`)
    REFERENCES `mydb`.`Employee of the Ministry of Education` (`idEmployee of the Ministry of Education`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employee of the Ministry of Education_has_University chang2`
    FOREIGN KEY (`University change request_idUniversity change request`)
    REFERENCES `mydb`.`University change request` (`idUniversity change request`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee of the Ministry of Education_has_scientific journey`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee of the Ministry of Education_has_scientific journey` (
  `Employee of the Ministry of Education_idEmployee of the Ministry of Education` INT NOT NULL,
  `scientific journey_idscientific journey` INT NOT NULL,
  PRIMARY KEY (`Employee of the Ministry of Education_idEmployee of the Ministry of Education`, `scientific journey_idscientific journey`),
  INDEX `fk_Employee of the Ministry of Education_has_scientific jou_idx` (`scientific journey_idscientific journey` ASC) VISIBLE,
  INDEX `fk_Employee of the Ministry of Education_has_scientific jou_idx1` (`Employee of the Ministry of Education_idEmployee of the Ministry of Education` ASC) VISIBLE,
  CONSTRAINT `fk_Employee of the Ministry of Education_has_scientific journ1`
    FOREIGN KEY (`Employee of the Ministry of Education_idEmployee of the Ministry of Education`)
    REFERENCES `mydb`.`Employee of the Ministry of Education` (`idEmployee of the Ministry of Education`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employee of the Ministry of Education_has_scientific journ2`
    FOREIGN KEY (`scientific journey_idscientific journey`)
    REFERENCES `mydb`.`scientific journey` (`idscientific journey`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee of the Ministry of Education_has_ postponement of scholarship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee of the Ministry of Education_has_ postponement of scholarship` (
  `Employee of the Ministry of Education_idEmployee of the Ministry of Education` INT NOT NULL,
  ` postponement of scholarship_id postponement of scholarship` INT NOT NULL,
  PRIMARY KEY (`Employee of the Ministry of Education_idEmployee of the Ministry of Education`, ` postponement of scholarship_id postponement of scholarship`),
  INDEX `fk_Employee of the Ministry of Education_has_ postponement _idx` (` postponement of scholarship_id postponement of scholarship` ASC) VISIBLE,
  INDEX `fk_Employee of the Ministry of Education_has_ postponement _idx1` (`Employee of the Ministry of Education_idEmployee of the Ministry of Education` ASC) VISIBLE,
  CONSTRAINT `fk_Employee of the Ministry of Education_has_ postponement of1`
    FOREIGN KEY (`Employee of the Ministry of Education_idEmployee of the Ministry of Education`)
    REFERENCES `mydb`.`Employee of the Ministry of Education` (`idEmployee of the Ministry of Education`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employee of the Ministry of Education_has_ postponement of2`
    FOREIGN KEY (` postponement of scholarship_id postponement of scholarship`)
    REFERENCES `mydb`.` postponement of scholarship` (`id postponement of scholarship`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
